### ISSUE TITLE
Resident keys not supported?

### ISSUE THREAD

**Issue by jerryc05** [PowerShell/openssh-portable#586] opened 2022-03-21 22:13 UTC
```
$ ssh -V
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.2
```
`ssh-keygen -t ed25519-sk` works perfectly, but when I try to use resident keys (generation works), it fails to import.
```
$ ssh-add -D
All identities removed.
$ ssh-add -K
Cannot download keys without provider
$ ssh-keygen -K
Enter PIN for authenticator:
You may need to touch your authenticator to authorize key download.
Unable to load resident keys: invalid format
```

**Comment by bagajjal** [comment] 2022-03-21 22:15
Duplicate of https://github.com/PowerShell/Win32-OpenSSH/issues/1915

**Closed as completed by bagajjal** 2022-03-21 22:15 UTC

**Comment by bagajjal** [comment] 2022-03-21 22:20
@jerryc05 - You need to run "ssh-keygen -K" in an elevated cmd.exe/powershell.exe

**Comment by theking2** [comment] 2024-08-07 15:36
> @jerryc05 - You need to run "ssh-keygen -K" in an elevated cmd.exe/powershell.exe

option requires an argument -- K
